from datetime import timedelta

CANCEL_MIN_HOURS_BEFORE_TRAINING = 2
CANCEL_MIN_DELTA = timedelta(hours=CANCEL_MIN_HOURS_BEFORE_TRAINING)

AUTO_BAN_HOURS_BEFORE_TRAINING = 2
AUTO_BAN_DELTA = timedelta(hours=AUTO_BAN_HOURS_BEFORE_TRAINING)
