"""add debts and bans

Revision ID: 61e11b4460f0
Revises: 2a960a757901
Create Date: 2025-12-18 19:09:18.930186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61e11b4460f0'
down_revision: Union[str, Sequence[str], None] = '2a960a757901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bans', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('bans', sa.Column('is_auto', sa.Boolean(), nullable=False))
    op.add_column('bans', sa.Column('lifted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('bans', 'type',
               existing_type=postgresql.ENUM('MANUAL', 'AUTO_DEBT', name='bantype'),
               type_=sa.Enum('MANUAL', 'AUTO', name='ban_type_enum'),
               existing_nullable=False)
    op.drop_column('bans', 'until')
    op.drop_column('bans', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bans', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('bans', sa.Column('until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('bans', 'type',
               existing_type=sa.Enum('MANUAL', 'AUTO', name='ban_type_enum'),
               type_=postgresql.ENUM('MANUAL', 'AUTO_DEBT', name='bantype'),
               existing_nullable=False)
    op.drop_column('bans', 'lifted_at')
    op.drop_column('bans', 'is_auto')
    op.drop_column('bans', 'is_active')
    # ### end Alembic commands ###
