"""add training_id to ratings

Revision ID: f6b38fb4810f
Revises: 8f3c2a1d9b71
Create Date: 2026-01-12 19:00:42.165587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6b38fb4810f'
down_revision: Union[str, Sequence[str], None] = '8f3c2a1d9b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.alter_column('debts', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_debts_status'), table_name='debts')
    op.drop_column('locations', 'address')
    op.drop_column('locations', 'longitude')
    op.drop_column('locations', 'name')
    op.drop_column('locations', 'metro')
    op.drop_column('locations', 'latitude')
    op.drop_column('locations', 'maps_url')
    op.drop_column('locations', 'video_url')
    op.add_column('notifications', sa.Column('text', sa.Text(), nullable=False))
    op.add_column('notifications', sa.Column('url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.add_column('ratings', sa.Column('points', sa.Integer(), server_default='0', nullable=False))
    op.drop_constraint(op.f('uq_ratings_training_user'), 'ratings', type_='unique')
    op.drop_constraint(op.f('ratings_training_id_fkey'), 'ratings', type_='foreignkey')
    op.drop_constraint(op.f('ratings_user_id_fkey'), 'ratings', type_='foreignkey')
    op.create_foreign_key(None, 'ratings', 'trainings', ['training_id'], ['id'])
    op.create_foreign_key(None, 'ratings', 'users', ['user_id'], ['id'])
    op.drop_column('ratings', 'updated_at')
    op.drop_column('ratings', 'comment')
    op.drop_column('ratings', 'value')
    op.alter_column('settings', 'value',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.create_index(op.f('ix_trainings_start_at'), 'trainings', ['start_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trainings_start_at'), table_name='trainings')
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.alter_column('settings', 'value',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('ratings', sa.Column('value', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('ratings', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ratings', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.create_foreign_key(op.f('ratings_user_id_fkey'), 'ratings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('ratings_training_id_fkey'), 'ratings', 'trainings', ['training_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_ratings_training_user'), 'ratings', ['training_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('ratings', 'points')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_column('notifications', 'url')
    op.drop_column('notifications', 'text')
    op.add_column('locations', sa.Column('video_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('maps_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('metro', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('locations', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_debts_status'), 'debts', ['status'], unique=False)
    op.alter_column('debts', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    # ### end Alembic commands ###
